name = "clearbudget"
compatibility_date = "2024-03-29"
pages_build_output_dir = "clearbudget"

[[d1_databases]]
binding = "DB"
database_name = "budget-db"
database_id = "d28e294b-a880-4ef9-8ea5-8ecd01b2df75"
